/*
 * Copyright 2001-2004 The Apache Software Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package test.wsdl.doclit_arrays;

import junit.framework.TestCase;
import java.io.File;

/**
 * Test case for Document Literal Arrays functionality.
 * 
 * This test validates:
 * 1. Java2WSDL generation from ArrayService class
 * 2. WSDL2Java generation of client stubs
 * 3. Proper handling of arrays in document literal style
 */
public class ArrayServiceTestCase extends TestCase {

    public ArrayServiceTestCase(String name) {
        super(name);
    }

    /**
     * Test that Java2WSDL generates a valid WSDL file from ArrayService
     */
    public void testJava2WSDLGeneration() throws Exception {
        // Check that the WSDL file was generated
        String workDir = System.getProperty("build.dir", "target");
        File wsdlFile = new File(workDir + "/work/test/wsdl/doclit_arrays/ArrayService.wsdl");
        
        assertTrue("ArrayService.wsdl should be generated by Java2WSDL", wsdlFile.exists());
        assertTrue("ArrayService.wsdl should not be empty", wsdlFile.length() > 0);
        
        // Read the WSDL content and verify it contains expected elements
        String wsdlContent = readFileContent(wsdlFile);
        
        // Verify the WSDL contains expected namespace
        assertTrue("WSDL should contain doclit_arrays namespace", 
                   wsdlContent.contains("http://doclit_arrays.wsdl.test/"));
        
        // Verify the WSDL contains Bean type definition
        assertTrue("WSDL should contain Bean type definition", 
                   wsdlContent.contains("Bean"));
        
        // Verify the WSDL is document literal style
        assertTrue("WSDL should be document literal style", 
                   wsdlContent.contains("style=\"document\""));
    }

    /**
     * Test that WSDL2Java generates client stubs
     */
    public void testWSDL2JavaGeneration() throws Exception {
        String workDir = System.getProperty("build.dir", "target");
        String packageDir = workDir + "/work/test/wsdl/doclit_arrays";
        
        // Check that client stub files were generated
        File serviceFile = new File(packageDir + "/ArrayService.java");
        File serviceLocatorFile = new File(packageDir + "/ArrayServiceLocator.java");
        
        // At least one of these should be generated (depending on WSDL2Java version)
        boolean stubsGenerated = serviceFile.exists() || serviceLocatorFile.exists();
        assertTrue("WSDL2Java should generate client stub files", stubsGenerated);
    }

    /**
     * Test ArrayService client interface functionality
     */
    public void testArrayServiceInterface() throws Exception {
        // Test that the ArrayService interface was generated correctly
        Class<?> serviceInterface = Class.forName("test.wsdl.doclit_arrays.ArrayService");
        assertNotNull("ArrayService interface should be generated", serviceInterface);
        assertTrue("ArrayService should be an interface", serviceInterface.isInterface());
        
        // Check that the interface has the expected methods
        boolean hasEchoStringMethod = false;
        boolean hasEchoBeanMethod = false;
        
        for (java.lang.reflect.Method method : serviceInterface.getMethods()) {
            if ("echoString".equals(method.getName())) {
                hasEchoStringMethod = true;
            }
            if ("echoBean".equals(method.getName())) {
                hasEchoBeanMethod = true;
            }
        }
        
        assertTrue("ArrayService should have echoString method", hasEchoStringMethod);
        assertTrue("ArrayService should have echoBean method", hasEchoBeanMethod);
    }

    /**
     * Test ArrayService client stub instantiation
     */
    public void testArrayServiceStubInstantiation() throws Exception {
        // Test that ArrayServiceServiceLocator can be instantiated
        ArrayServiceServiceLocator locator = new ArrayServiceServiceLocator();
        assertNotNull("ArrayServiceServiceLocator should be instantiable", locator);
        
        // Test that we can get the service interface (without actually connecting)
        // Note: We can't call getDocArrays() here as it tries to connect to the actual service
        // Instead, we test that the locator has the expected methods
        assertNotNull("Service locator should provide address", locator.getDocArraysAddress());
        assertEquals("Service locator should have correct default address", 
                     "http://localhost:8080/axis/services/DocArrays", 
                     locator.getDocArraysAddress());
    }

    /**
     * Test that the deploy.wsdd file exists and has correct content
     */
    public void testDeploymentDescriptor() throws Exception {
        File deployFile = new File("src/test/java/test/wsdl/doclit_arrays/deploy.wsdd");
        assertTrue("deploy.wsdd should exist", deployFile.exists());
        
        String deployContent = readFileContent(deployFile);
        assertTrue("deploy.wsdd should contain correct service name", 
                   deployContent.contains("DocArrays"));
        assertTrue("deploy.wsdd should contain correct className", 
                   deployContent.contains("test.wsdl.doclit_arrays.ArrayService"));
        assertTrue("deploy.wsdd should be document style", 
                   deployContent.contains("style=\"document\""));
    }

    /**
     * Helper method to read file content
     */
    private String readFileContent(File file) throws Exception {
        StringBuilder content = new StringBuilder();
        java.io.BufferedReader reader = new java.io.BufferedReader(
            new java.io.FileReader(file));
        String line;
        while ((line = reader.readLine()) != null) {
            content.append(line).append("\n");
        }
        reader.close();
        return content.toString();
    }
}